### ISSUE TITLE
Feature request / Suggestion -> Transform to lowercase with advanced options

### ISSUE THREAD

**Issue by Ares9323** [d-akara/vscode-extension-transformer#39]
Hello, I've been using your extension for almost a year and I find it very useful.
I'm Italian and unfortunately we have, like many other languages, accents!

It would be very useful to have a command like: "Remove accented characters"
If you are interested in the past I have updated an existing list in an extension called "accent-neutralise", [here](https://github.com/DataTables/Plugins/pull/441/files) you can find the most common characters that need to be replaced.

Another useful thing would be replacing spaces with underscores.
In database tables i use lowercase names separated with underscores and they should not contain accented or special characters.

Example: Quantità art. -> quantita_art

If you think this could be implemented in your extension I could try to fork it and provide some help, just tell me if you think it's possible 👍 

Thank you for your work! Have a nice day

**Comment by dakaraphi** [comment]
@Ares9323 just published version 1.11 which has `Normalize Diacritical Marks (remove accents)` command.
Give it a try and let me know if works for your use case.

**Comment by Synthetica9** [comment]
> Another useful thing would be replacing spaces with underscores.

I use another extension that does this (and more), which might also work for you. The extension is [change-case](https://marketplace.visualstudio.com/items?itemName=wmaurer.change-case) which has the `Change Case snake` which changes `Quantità art` to `quantità_art`, where you could then use this extension to remove the diacritics. Perhaps you could write a macro of some sort to do both those steps if you use it often enough

**Comment by Ares9323** [comment]
> > Another useful thing would be replacing spaces with underscores.
> 
> I use another extension that does this (and more), which might also work for you. The extension is [change-case](https://marketplace.visualstudio.com/items?itemName=wmaurer.change-case) which has the `Change Case snake` which changes `Quantità art` to `quantità_art`, where you could then use this extension to remove the diacritics. Perhaps you could write a macro of some sort to do both those steps if you use it often enough

I also use an extension for camelCase, PascalCase, kebab-case, snake_case and Title Case but unfortunately I am Italian and my collaborators can't really understand they don't have to use accents in some fields 🤣
I can't wait to test the new accent neutralise feature!
