### ISSUE TITLE
Feature Request - Add Characters to Selected Lines

### ISSUE THREAD

**Issue by faceruler** [d-akara/vscode-extension-transformer#46]
I love this extension and use it daily.  Thank  you for your hard work.

A helpful feature would be the ability to select lines and add one character to the end of each line - like a comma.

before
-------
1
2
3
4

after
------
1,
2,
3,
4,

Another helpful feature be the ability to select lines and add characters before and after each line (example below).  

before
-------
1
2
3
4

after
------
array.Add("1");
array.Add("2");
array.Add("3");
array.Add("4");

**Comment by Synthetica9** [comment]
This functionality already exists natively in VSCode through multi editing, I don't think it's necessary to add it

**Comment by d-akara** [comment]
This capability already exists using multi cursors in vscode.  I don't think I could add anything to make it better.
