### ISSUE TITLE
A teeny-tiny problem on Marketplace page

### ISSUE THREAD

**Issue by alircxa** [d-akara/vscode-extension-transformer#51]
Hello @d-akara

There is a teeny-tiny problem with loading Align To Cursor screenshot on the marketplace page.
Look at this:

![2021-08-29 22_07_39-Window](https://user-images.githubusercontent.com/8685650/131259955-e9ac355a-990f-46e7-9c19-4d93efd0b5f4.png)

I think when you rename their names, you forget to capitalize the first letter of the "Align To Cursor"s name. Based on your directory it must be: [https://raw.githubusercontent.com/d-akara/vscode-extension-transformer/master/readme-images/Align-to-cursor.png](https://raw.githubusercontent.com/d-akara/vscode-extension-transformer/master/readme-images/Align-to-cursor.png)

Regards.

**Comment by d-akara** [comment]
Thanks, will get it fixed in next update
