### ISSUE TITLE
"as New document" overwrites existing temporary document

### ISSUE THREAD

**Issue by gangefors** [d-akara/vscode-extension-transformer#53]
1. Create a new document and add a few lines in the untitled document
2. Run "Unique lines as New document", this opens a new document named "transform-Untitled-1"
3. Close "Untitled-1" document editor (the one we created in step 1)
4. Create a new document, this editor gets the same temporary name as the one we created in step 1 namely "Untitled-1". This would be identical to replacing the content of the existing editor.
5. Add lines and execute "Unique lines as New document" again. This will now overwrite the content in "transform-Untitled-1" which is not desirable. The action specifically says I will get a new document.

I would rather have the transformation action never reuses an open editor but instead create a new one with a unique name.
The current behaviour makes it harder to work with text in unsaved documents.

**Comment by d-akara** [comment]
Fixed in 1.12.1

**Comment by gangefors** [comment]
That was fast. Thanks for a great extension. Found it recently and it solves basically all my text transformation needs.

I noted that a typo of the version slipped through in the change log, 1.11.1 instead of 1.12.1.
